name: eco_smart
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.4
  dio: ^5.7.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.6
  connectivity_plus: ^5.0.2
  mask_text_input_formatter: ^2.9.0
  flutter_svg: ^2.0.10+1
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  get_it: ^7.6.7
  cached_network_image: ^3.3.1
  shimmer: ^2.0.0
  easy_localization: ^3.0.7
  carousel_slider: ^5.0.0
  page_transition: ^2.1.0
  gradient_borders: ^1.0.1
  image_picker: ^1.1.2

  change_app_package_name: ^1.4.0

  #firebase
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  firebase_storage: ^12.4.1
  firebase_messaging: ^15.2.1
  cloud_firestore: ^5.6.2
  firebase_crashlytics: ^4.3.1
  google_sign_in: ^6.2.2
  path_provider: ^2.1.5


#  new
  avatar_glow: ^3.0.1
  stories_for_flutter: ^1.2.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/font/
    - assets/icons/
    - assets/languages/


  fonts:
    - family: GolosText
      fonts:
        - asset: assets/font/GolosText-Black.ttf
        - asset: assets/font/GolosText-Bold.ttf
        - asset: assets/font/GolosText-ExtraBold.ttf
        - asset: assets/font/GolosText-Medium.ttf
        - asset: assets/font/GolosText-Regular.ttf
        - asset: assets/font/GolosText-SemiBold.ttf
